### ISSUE TITLE
How to use the package

### ISSUE THREAD

**Issue by chookity-pokk** [skissue/meow-tree-sitter#1]
I am a dummy so bare with me. I installed the package and added the below into my init, I opened up a python project and hit `f`, which I thought would activate `(meow-tree-sitter-register-thing ?f "function")` but it instead activates `meow`'s `find` function. 

Any help would be greatly appreciated.

```
(add-to-list 'load-path "~/.emacs.d/lisp/meow-tree-sitter")
(require 'meow-tree-sitter)
(meow-tree-sitter-register-thing ?f "function")
(meow-tree-sitter-register-thing ?C "class")
(meow-tree-sitter-register-thing ?/ "comment")
```

Also, I am on the most up to date version of `meow` and Emacs, for what that's worth.

**Comment by skissue** [comment]
By default, keybinds are registered to Meow's "thing" registry, which is used by `meow-bounds-of-thing` and `meow-inner-of-thing`, which I believe are bound to `.` and `,` by default. Thus, for a function, it should be `.f` rather than just `f`.

Should probably make this clearer in the README, I wrote it a bit hastily... :sweat_smile:

**Comment by chookity-pokk** [comment]
Oh, I am a dummy haha. Now it is working just fine! Thank you for the nice package and the quick reply!
